(function(){
const LEVELS=["A1","A2","B1","B2","C1"];
const day=()=>new Date().toISOString().slice(0,10);
function S(){store.sf36=store.sf36||{};let s=store.sf36;if(s.date!==day()){s.date=day();s.tasks={review:false,new:false,tutor:false,listen:false}}s.tasks=s.tasks||{review:false,new:false,tutor:false,listen:false};s.tutor=s.tutor||{attempts:0,total:0,avg:0};s.listen=s.listen||{attempts:0,correct:0};s.week=s.week||{started:day(),done:0,goal:20};return s}
function items(){return COURSES.flatMap(c=>c.items.map(x=>({text:x[0],tr:x[1],course:c})))}
function weak(){const m=store.review||{},now=Date.now();return items().map(x=>{const r=m[x.text]||{},best=typeof r.best==="number"?r.best:null,due=typeof r.due==="number"&&r.due<=now;let p=(due?40:0)+(best==null?15:100-best)+(!store.done.includes(x.text)?10:0);return {...x,r,best,due,p}}).filter(x=>x.best!==null||x.due||!store.done.includes(x.text)).sort((a,b)=>b.p-a.p)}
function fresh(){return items().filter(x=>x.course.level===store.level&&!store.done.includes(x.text)).sort((a,b)=>{let w=weak(),ia=w.findIndex(z=>z.text===a.text),ib=w.findIndex(z=>z.text===b.text);return ia-ib})}
function q36(x){return "'"+jsq(String(x))+"'"}
function esc36(x){return typeof esc==="function"?esc(String(x)):String(x).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}
function skills(){let total=COURSES.reduce((n,c)=>n+c.items.length,0),done=store.done.length,rs=Object.values(store.review||{}).filter(r=>typeof r.best==="number"),sp=rs.length?Math.round(rs.reduce((n,r)=>n+r.best,0)/rs.length):0,s=S(),due=Object.values(store.review||{}).filter(r=>r.due&&r.due<=Date.now()).length;return{total,done,pct:Math.round(done/total*100),speaking:sp,due,conversation:s.tutor.avg,reviewed:rs.length}}
function cardSkill(i,t,v,d){return '<div class="sfSkill"><div class="sfSkillTop"><span>'+i+'</span><b>'+t+'</b><strong>'+v+'%</strong></div><div class="meter"><i style="width:'+Math.min(100,Math.max(0,v))+'%"></i></div><small>'+d+'</small></div>'}
function openPhrase(t){let h=items().find(x=>x.text===t);if(!h)return;current=h.course;lessonPhase=0;lessonScore=null;lessonFinished=false;renderLesson(h.course.items.findIndex(x=>x[0]===t))}
window.sfOpenPhrase=openPhrase;
function mark(k){let s=S();if(!s.tasks[k]){s.tasks[k]=true;s.week.done++;save()}}
function plan(){let w=weak(),f=fresh(),s=typeof TUTOR_SCENARIOS!=="undefined"?TUTOR_SCENARIOS:[],id={conversation:"social",travel:"airport",work:"meeting",daily:"supermarket"}[store.goal]||"social",t=s.find(x=>x.id===id)||s[0];return{review:w.filter(x=>x.best!==null||x.due).slice(0,3),fresh:f.slice(0,3),tutor:t,listen:f[0]||w[0]||items()[0]}}
function today36(){
 let s=S(),p=plan(),st=skills(),n=Object.values(s.tasks).filter(Boolean).length,w=p.review.map(x=>'<button class="sfMistake" onclick="sfOpenPhrase('+q36(x.text)+')"><span>'+(x.best<70?"🔴":x.best<90?"🟡":"🟢")+'</span><div><b>'+esc36(x.text)+'</b><small>'+esc36(x.course.title)+' · '+(x.best==null?"новая":x.best+"%")+'</small></div><strong>→</strong></button>').join("");
 let rb=p.review.length?'<button class="primary sfFull" onclick="sf36Task(\\'review\\');smartReview()">🔴 Повторить слабые <span>'+p.review.length+'</span></button>':'<button class="secondary sfFull" onclick="go(\\'learn\\')">🧠 Smart Review · всё выполнено</button>';
 let nb=p.fresh.length?'<button class="secondary sfFull" onclick="sfOpenPhrase('+q36(p.fresh[0].text)+')">🆕 Новая фраза <small>'+esc36(p.fresh[0].course.title)+'</small></button>':'<button class="secondary sfFull" onclick="go(\\'learn\\')">🆕 Уровень пройден</button>';
 let tb=p.tutor?'<button class="secondary sfFull" onclick="sf36Task(\\'tutor\\');startTutor('+q36(p.tutor.id)+')">🗣️ Диалог · '+esc36(p.tutor.title)+'</button>':'<button class="secondary sfFull" onclick="go(\\'tutor\\')">🗣️ Диалоги</button>';
 shell('<section class="hero sfHero"><div class="eyebrow">Персональный план · '+store.minutes+' мин</div><h1>Сегодня — именно то, что нужно</h1><p>'+esc36(goalName(store.goal))+' · уровень '+store.level+'. План меняется по твоим результатам.</p><div class="sfDaily"><b>'+n+' / 4</b><span>задачи сегодня</span><div class="meter"><i style="width:'+n*25+'%"></i></div></div></section><div class="card"><div class="sfSectionHead"><div><div class="eyebrow">🎯 План на сегодня</div><h3>4 коротких шага</h3></div><span class="sfBadge">'+(4-n)+' осталось</span></div>'+rb+nb+tb+'<button class="secondary sfFull" onclick="sf36Task(\\'listen\\');listenQuiz()">🎧 Аудирование · 3 вопроса</button></div><div class="card"><div class="eyebrow">🔎 Анализ</div><h3>Мои слабые места</h3>'+(w||'<div class="empty">Данных пока мало. Продолжай практику.</div>')+'</div><div class="card"><div class="sfSectionHead"><div><div class="eyebrow">📊 Профиль навыков</div><h3>Твой прогресс</h3></div><button class="miniBtn" onclick="go(\\'profile\\')">Подробнее</button></div>'+cardSkill("🗣️","Говорение",st.speaking,st.reviewed?st.reviewed+" проверок":"Начни говорить")+cardSkill("💬","Диалоги",st.conversation,s.tutor.attempts?s.tutor.attempts+" реплик":"Пройди Tutor")+cardSkill("📚","Словарь",st.pct,st.done+" из "+st.total+" фраз")+'</div><div class="card"><div class="eyebrow">🔥 Мотивация</div><div class="statGrid"><div class="statBox"><b>'+store.streak+'</b><div class="small">дней подряд</div></div><div class="statBox"><b>'+store.xp+'</b><div class="small">XP</div></div><div class="statBox"><b>'+s.week.done+'/20</b><div class="small">цель недели</div></div></div><button class="secondary full" onclick="go(\\'profile\\')">📈 Мой прогресс и ошибки</button></div>')
}
function profile(){
 let st=skills(),s=S(),rows=LEVELS.map(l=>{let q=levelStats(l);return '<div class="sfLevelRow"><b>'+l+'</b><div class="meter"><i style="width:'+q.pct+'%"></i></div><span>'+q.pct+'%</span></div>'}).join(""),m=weak().slice(0,10).map(x=>'<button class="sfMistake" onclick="sfOpenPhrase('+q36(x.text)+')"><span>'+(x.best==null?"⚪":x.best<70?"🔴":x.best<90?"🟡":"🟢")+'</span><div><b>'+esc36(x.text)+'</b><small>'+esc36(x.course.title)+' · '+(x.best==null?"нет попытки":x.best+"%")+(x.due?" · повторить":"")+'</small></div><strong>→</strong></button>').join("");
 shell('<section class="hero"><div class="eyebrow">Мой English · Personal Profile</div><h1>Твой учебный профиль</h1><p>Результаты речи, диалогов, повторений и обучения собираются в одной картине.</p><div class="score">'+st.pct+'%</div><div class="small" style="text-align:center">общий прогресс по '+st.total+' фразам</div></section><div class="card">'+cardSkill("🗣️","Говорение",st.speaking,st.reviewed?"Средний результат":"Пока нет результатов")+cardSkill("💬","Разговор",st.conversation,s.tutor.attempts?s.tutor.attempts+" реплик":"Пройди диалог")+cardSkill("🔁","Повторение",st.due?Math.max(0,100-st.due*10):100,st.due?st.due+" ждут повторения":"Всё в порядке")+cardSkill("📚","Словарь",st.pct,st.done+" из "+st.total)+'</div><div class="card"><div class="eyebrow">🗺️ Уровни</div>'+rows+'</div><div class="card"><div class="sfSectionHead"><div><div class="eyebrow">🧠 База ошибок</div><h3>Что повторить</h3></div><span class="sfBadge">'+m.length+'</span></div>'+(m||'<div class="empty">Ошибок пока нет.</div>')+'</div><div class="card"><div class="eyebrow">🎧 Аудио</div><h3>Записи и скорость</h3><p class="muted">12 фраз имеют готовые WAV. Остальные озвучиваются браузером. Это честно отделено от нативных записей.</p><div class="sfAudioStats"><b>12</b><span>WAV</span><b>'+Math.max(0,st.total-12)+'</b><span>browser voice</span></div></div><div class="card"><div class="eyebrow">🚗 В дороге</div><h3>Drive Mode</h3><p class="muted">Только крупные кнопки и прослушивание. Для безопасности не требует ввода текста.</p><button class="primary full" onclick="driveMode()">▶ Запустить Drive Mode</button></div>')
}
function playText(t,r){let src=AUDIO[t];if(src){let a=new Audio(src);a.playbackRate=r||1;a.play().catch(()=>{});return}if("speechSynthesis"in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang="en-US";u.rate=r||1;speechSynthesis.speak(u)}}
function listenQuiz(){let p=items().filter(x=>x.course.level===store.level).sort(()=>Math.random()-.5).slice(0,3);window.sfListen={pool:p,index:0,score:0,rate:1};renderListen()}
window.listenQuiz=listenQuiz;
function renderListen(){let q=sfListen;if(!q||q.index>=q.pool.length){finishListen();return}let it=q.pool[q.index],o=[it.tr,...items().filter(x=>x.tr!==it.tr).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.tr)].sort(()=>Math.random()-.5);shell('<div class="lessonTop"><button class="back" onclick="go(\\'today\\')">← Сегодня</button><span class="lessonCount">🎧 '+(q.index+1)+' / 3</span></div><div class="card lessonCard sfListenCard"><div class="eyebrow">Аудирование · '+store.level+'</div><div class="miniMeter"><i style="width:'+Math.round(q.index/3*100)+'%"></i></div><h2>Что ты услышал?</h2><p class="muted">Послушай английскую фразу и выбери перевод.</p><button class="sfListenCircle" onclick="sfPlay()">🔊</button><div class="sfSpeed"><button class="'+(q.rate===.75?"on":"")+'" onclick="sfListen.rate=.75;renderListen()">0.75×</button><button class="'+(q.rate===1?"on":"")+'" onclick="sfListen.rate=1;renderListen()">1×</button><button class="'+(q.rate===1.25?"on":"")+'" onclick="sfListen.rate=1.25;renderListen()">1.25×</button></div><div class="sfChoices">'+o.map(x=>'<button class="choice" onclick="answerListen('+q36(x)+','+q36(it.tr)+')">'+esc36(x)+'</button>').join("")+'</div></div>');window.sfPlay=()=>playText(it.text,q.rate);setTimeout(()=>playText(it.text,q.rate),250)}
window.answerListen=function(a,c){let q=sfListen;if(!q)return;let ok=a===c;if(ok)q.score++;S().listen.attempts++;if(ok)S().listen.correct++;save();toast(ok?"✓ Правильно":"↻ Не совсем");setTimeout(()=>{q.index++;renderListen()},400)};
function finishListen(){let q=sfListen,p=Math.round(q.score/(q.pool.length||1)*100);S().listen.last=p;save();shell('<section class="hero"><div class="eyebrow">🎧 Аудирование</div><h1>'+p+'%</h1><p>Правильных ответов: <b>'+q.score+' из '+q.pool.length+'</b>.</p><div class="card"><h3>'+(p>=80?"Отлично! 🎉":"Повторим ещё раз")+'</h3><p class="muted">Меняй скорость и проходи короткие серии.</p><button class="primary full" onclick="listenQuiz()">🔁 Ещё 3 вопроса</button><button class="secondary full" onclick="go(\\'today\\')">← К плану</button></div></section>')}
window.finishListen=finishListen;
function driveMode(){let p=items().filter(x=>x.course.level===store.level&&!store.done.includes(x.text)).slice(0,8);window.sfDrive={pool:p.length?p:items().filter(x=>x.course.level===store.level).slice(0,8),index:0,rate:1};renderDrive()}
function renderDrive(){let d=sfDrive;if(!d||!d.pool.length){go("today");return}let x=d.pool[d.index];shell('<section class="hero sfDrive"><div class="eyebrow">🚗 Drive Mode · '+store.level+'</div><h1>Слушай → повторяй вслух</h1><p>'+ (d.index+1)+' из '+d.pool.length+' · '+esc36(x.course.title)+'</p><div class="sfDrivePhrase">'+esc36(x.text)+'</div><button class="sfDrivePlay" onclick="sfPlayDrive()">🔊</button><div class="sfSpeed"><button class="'+(d.rate===.75?"on":"")+'" onclick="sfDrive.rate=.75;renderDrive()">0.75×</button><button class="'+(d.rate===1?"on":"")+'" onclick="sfDrive.rate=1;renderDrive()">1×</button><button class="'+(d.rate===1.25?"on":"")+'" onclick="sfDrive.rate=1.25;renderDrive()">1.25×</button></div><button class="primary full" onclick="sfNextDrive()">Следующая фраза →</button><button class="secondary full" onclick="go(\\'today\\')">Завершить</button></section>');window.sfPlayDrive=()=>playText(x.text,d.rate);window.sfNextDrive=()=>{d.index<d.pool.length-1?(d.index++,renderDrive()):go("today")};setTimeout(()=>playText(x.text,d.rate),250)}
window.driveMode=driveMode;
function go36(x){page=x;({today:today36,learn:learn,tutor:tutor,english:english,profile:profile,listen:listenQuiz,drive:driveMode}[x]||today36)()}
window.go=go36;window.today=today36;window.profile=profile;
window.sf36Task=function(k){mark(k);today36()};
if(!window.__sf36Wrap){window.__sf36Wrap=true;let old=window.finishTutor;window.finishTutor=function(){try{let s=S(),avg=tutorScenario&&tutorScenario.turns.length?Math.round(tutorScore/tutorScenario.turns.length):0;s.tutor.attempts+=tutorScenario?tutorScenario.turns.length:0;s.tutor.total+=tutorScore;s.tutor.avg=s.tutor.attempts?Math.round(s.tutor.total/s.tutor.attempts):0;save()}catch(e){}mark("tutor");return old.apply(this,arguments)}}
try{today36()}catch(e){console.error(e)}
})();